version: '3'
services:
  web:
    build: .
    container_name: easywork_be
    restart: always
    volumes:
      - ./api_server:/server
      - ./data/log/node:/root/.npm/_logs/
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: easywork_mysql
    restart: always
    volumes:
      # 数据
      - ./data/mysql/data:/var/lib/mysql
      # 日志
      - ./data/log/mysql:/var/log/mysql
      # 配置
      - ./data/mysql/conf:/etc/mysql/conf.d
    command:
      [
        'mysqld',
        '--innodb-buffer-pool-size=80M',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00',
      ]
    # ports:
    #   - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
  nginx:
    image: nginx:latest
    container_name: easywork_nginx
    restart: always
    volumes:
      - ./conf/nginx/:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
      - ./templates:/var/www
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    depends_on:
      - web