version: '3'
services:
  web:
    build: .
    ports:
      - "0.0.0.0:9000:3007"
    volumes:
      - ./api_server:/server
      - ./log:/root/.npm/_logs/
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    expose:
      - "3306"
    
volumes:
  logvolume01: {}